services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: DragonBall
      POSTGRES_USER: goku
      POSTGRES_PASSWORD: 1234
    volumes:
      - ../db:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  web:
    build: ./transback
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./transback:/app
      - ./transback/static:/app/static  # Django statik dosyaları
      - ./transback/profile_pictures:/app/profile_pictures  # Django profil resimleri
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE: postgres
      SQL_HOST: db
      SQL_PORT: 5432
      SQL_USER: your_db_user
      SQL_PASSWORD: your_db_password
    networks:
      - app-network
    
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./front:/usr/share/nginx/html  # Frontend dosyalarının Nginx ile paylaşımı
      - ./transback/static:/static  # Django statik dosyaları
      - ./transback/profile_pictures:/profile_pictures  # Django profil resimleri
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
