services:
  db:
    image: postgres
    volumes:
      - ../db:/var/lib/postgresql/data
      - shared-data:/vault/token/
    depends_on:
      - vault
    networks:
      - app-network
    ports:
      - "5432:5432"

  web:
    build: ./transback
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./transback:/app
      - ./transback/static:/app/static  # Django statik dosyaları
      - ./transback/profile_pictures:/app/profile_pictures  # Django profil resimleri
      - ./transback/transbackend/templates:/app/templates  # Django template dosyaları
      - ./transback/locale:/app/locale  # Django çeviri dosyaları
      - ssl-certs:/etc/nginx/ssl/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - vault
    networks:
      - app-network
    
  nginx:
    build:
      context: ./nginx  # Dockerfile kullanılarak imaj oluşturulacak
    volumes:
      - ./front:/usr/share/nginx/html  # Frontend dosyalarının Nginx ile paylaşımı
      - ./transback/static:/static  # Django uygulamasının statik dosyaları
      - ./transback/profile_pictures:/profile_pictures  # Django profil resimleri
      - ./nginx-logs/modsec:/var/log/modsec # Dizin montajı
      - ssl-certs:/etc/nginx/ssl/  # Sertifikaları paylaşma
    environment:
      - BACKEND=http://web:8000  # Backend servisine bağlantı adresi
      - VAULT_ADDR=http://vault:8201  # Vault sunucusuna bağlantı adresi
      - VAULT_TOKEN_FILE=/vault/token/root_token.txt  # Vault kimlik doğrulama token dosyası
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - vault
    networks:
      - app-network


  vault:
    build:
      context: ./vault
    cap_add:
      - IPC_LOCK
    volumes:
      - shared-data:/vault/token/
    env_file:
      - ./transback/.env
    ports:
      - "8300:8300"
    networks:
      - app-network
    environment:
      VAULT_ADDR: http://localhost:8300
      restart: on-failure


  splunk-forwarder:
    image: splunk/universalforwarder:latest
    container_name: splunk_forwarder
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_SERVER=45.9.30.21:8088  # Splunk'ın HTTP Event Collector (HEC) adresi
      - SPLUNK_TOKEN=af30f512-baba-43d9-867d-3d5b27ed33e1  
      # HEC için belirlenen token
      - SPLUNK_PASSWORD=2537131Marufg.  # Splunk yönetici şifresi
    volumes:
      - ./splunk-config:/opt/splunkforwarder/etc/system/local  # Splunk yapılandırma dosyalarının bağlı olduğu dizin
      - ./nginx-logs/modsec:/var/log/modsec # Dizin montajı

    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  shared-data:
  ssl-certs:
