services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: DragonBall
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
    volumes:
      - ../db:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"

  web:
    build: ./transback
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./transback:/app
      - ./transback/static:/app/static  # Django statik dosyaları
      - ./transback/profile_pictures:/app/profile_pictures  # Django profil resimleri
      - ./transback/transbackend/templates:/app/templates  # Django template dosyaları
      - ./transback/locale:/app/locale  # Django çeviri dosyaları
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      SQL_DB: DragonBall
      SQL_HOST: db
      SQL_PORT: 5432
      SQL_USER: admin
      SQL_PASSWORD: 1234
    networks:
      - app-network
    
  nginx:
    build:
      context: ./nginx  # Dockerfile'ı kullanarak image'ı oluşturacak
    volumes:
      - ./front:/usr/share/nginx/html  # Frontend dosyalarının Nginx ile paylaşımı
      - ./transback/static:/static  # Django statik dosyaları
      - ./transback/profile_pictures:/profile_pictures  # Django profil resimleri
    environment:
      - BACKEND=http://web:8000
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app-network

  vault:
    build: 
        context: ./vault
    cap_add:
      - IPC_LOCK
    volumes:
      - shared-data:/vault/token/
    env_file:
      - ./transback/.env
    ports:
      - "8300:8300"
    networks:
      - app-network
    environment:
      VAULT_ADDR: http://localhost:8300
      restart: on-failure

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  shared-data:
